language: ruby
matrix:
  include:
  - rvm: ruby-head
  - rvm: 2.3.0
  - rvm: 2.3.0
    services:
      - docker
    script:
      - docker build -t mozilla/ssh_scan .
      - >
          if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then \
            docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" ;\
            docker push mozilla/ssh_scan:latest ;\
          else \
            exit 0 ;\
          fi
  - rvm: 2.3.0
    script:
      - gem install ssh_scan
      - chmod 755 ./spec/ssh_scan/integration.sh
      - ./spec/ssh_scan/integration.sh
  - rvm: 2.3.0
    script:
      - chmod 755 ./spec/ssh_scan/integration.sh
      - ./spec/ssh_scan/integration.sh
  - rvm: 2.2.0
  - rvm: 2.1.3
  - rvm: 2.0.0
